server:
  port: 8065
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka/
  instance:
    # 设置心跳的时间间隔（默认是30秒）
    lease-renewal-interval-in-seconds: 5
    # 如果现在超过了5秒的间隔（默认是90秒）超时间隔
    lease-expiration-duration-in-seconds: 10
    # 在信息列表时显示主机名称
    instance-id: localhost
    # 访问的路径变为IP地址
    prefer-ip-address: true
spring:
  cloud:
    stream:
      #要使用时先安装rabbitmq 然后在sbin目录执行:rabbitmq-plugins enble rabbitmq_management 启用web管理工具 运行:rabbitmq-server.bat 访问127.0.0.1:15672 guest guest 即可管理
      # 多个binder时必须指定一个默认的binder，如果不配置将报错
      default-binder: boss
      # 在此处配置要绑定的rabbitmq的服务信息
      binders:
         # 表示定义的名称，用于binding整合
        boss:
          # 消息组件类型
          type: rabbit
          # 设置rabbitmq的相关的环境配置
          environment:
            spring:
              rabbitmq:
                  addresses: 127.0.0.1
                  port: 15672
                  username: guest
                  password: guest
                  virtual-host: boss
      bindings:
        #服务整合处理 outputmsg 为自定义 生产通道名 指定生产通道是要与此一致
        outputmsg:
          # 表示要使用的Exchange 交换器名称定义
          destination: myExchange
          ## 设置消息类型，本次为对象json，如果是文本则设置“text/plain”
          content-type: application/json
          ## 设置要绑定的消息服务的具体设置
          binder: defaultRabbit
      rabbit:
        bindings:
          outputmsg:
            producer:
              #exchange的类型为广播模式
              exchangeType: fanout
  application:
    name: streampro
  rabbitmq:
    addresses: 127.0.0.1
    port: 15672
    username: guest
    password: guest
    virtual-host: boss