server:
  port: 8067
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka/
  instance:
    # 设置心跳的时间间隔（默认是30秒）
    lease-renewal-interval-in-seconds: 5
    # 如果现在超过了5秒的间隔（默认是90秒）超时间隔
    lease-expiration-duration-in-seconds: 10
    # 在信息列表时显示主机名称
    instance-id: localhost
    # 访问的路径变为IP地址
    prefer-ip-address: true
spring:
  cloud:
    stream:
      #此属性用于设置默认值，contentType只是示例
      default:
        contentType: application/json
      #要使用时先安装rabbitmq 然后在sbin目录执行:rabbitmq-plugins enble rabbitmq_management 启用web管理工具 运行:rabbitmq-server.bat 访问127.0.0.1:15672 guest guest 即可管理
      # 多个binder时必须指定一个默认的binder，如果不配置将报错
      default-binder: boss
      # 在此处配置要绑定的rabbitmq的服务信息
      binders:
         # 表示定义的名称，用于binding整合
        boss:
          # 消息组件类型
          type: rabbit
          # 设置rabbitmq的相关的环境配置
          environment:
            spring:
              rabbitmq:
                  addresses: 127.0.0.1
                  port: 15672
                  username: guest
                  password: guest
                  virtual-host: boss
      bindings:
        #服务整合处理 outputmsg 为自定义 生产通道名 指定生产通道是要与此一致
        outputmsg:
          # 表示要使用的Exchange 交换器名称定义
          destination: cus
          ## 设置消息类型，本次为对象json，如果是文本则设置“text/plain” @ServiceActivator注解 和 @StreamListener 都实现了对消息的监听，ServiceActivator 没有内置消息转换，需要自己实现转换 @StreamListener 不需要自己实现，只需要在配置文件增加spring.cloud.stream.bindings.input.content-type=application/json 属性(默认支持json，json格式的可以不用配置)
          content-type: application/json
          ## 设置要绑定的消息服务的具体设置
          binder: boss
        #服务整合处理 outputmsg 为自定义 生产通道名 指定生产通道是要与此一致
        inputmsg:
          # 表示要使用的Exchange 交换器名称定义
          destination: pro
          #设置分组 保证每个消息只被一个实例消费
          group: grouptra
          ## 设置消息类型，本次为对象json，如果是文本则设置“text/plain”
          content-type: application/json
          ## 设置要绑定的消息服务的具体设置
          binder: boss
      rabbit:
        bindings:
          outputmsg:
            producer:
              #exchange的类型为广播模式
              exchangeType: fanout
  application:
    name: streampro
  rabbitmq:
    addresses: 127.0.0.1
    port: 15672
    username: guest
    password: guest
    virtual-host: boss
    #生产端
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    #消费端
    listener:
      simple:
        acknowledge-mode: manual
        #初始连接数量
        concurrency: 5
        #最大连接数量
        max-concurrency: 10
        #限流
        prefetch: 1
#官方两个实例配置示例
#spring:
#  cloud:
#    stream:
#      bindings:
#        input:
#          destination: foo
#          binder: rabbit1
#        output:
#          destination: bar
#          binder: rabbit2
#      binders:
#        rabbit1:
#          type: rabbit
#          environment:
#            spring:
#              rabbitmq:
#                host: <host1>
#        rabbit2:
#          type: rabbit
#          environment:
#            spring:
#              rabbitmq:
#                host: <host2>